### ISSUE TITLE
TestCase強化しました

### ISSUE THREAD

**Issue by gfx** [yosuke-furukawa/jsx_test_tutorial#1]
http://yosuke-furukawa.hatenablog.com/entry/2013/12/21/202211 へのフィードバックですが、長文になるのでここで。
## TestCase#toEqual() がMapをとれるようになりました

関数テンプレートがなかった時代からアップデートされていなかっただけでした。
toEqual()はequals()にそのまま移譲するだけとなり、組み込みクラスの Array.<T>, Map.<T> についてデータ構造のテストを行えます。
## TestCase#setUp(:AsyncContext) / #tearDown(:AsyncContext)

非同期テスト用の setUp() / tearDown() です。非同期テストをする場合はこちらを使ってください。

使い方はこんな感じです。 async.name() はそのテストケースにおいてユニークなので、テストメソッド固有のデータを保存するときのキーとして使えます。
- https://github.com/jsx/JSX/blob/master/t/lib/015.test-case-callbacks-async.jsx
## gruntについて

jsx --test を直接使うのではなく、 `prove(1)` を介してテストするのがお勧めです。
そのほうが -j で並行にテストできますし、テストの出力もシンプルにできます。

**Comment by yosuke-furukawa** [comment]
反映しましたー！
